##
## Copyright (c) 2022-2023 Geosiris.
## SPDX-License-Identifier: Apache-2.0
##
---

name: Publish (pypiTest)
on: [push,pull_request]

jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install poetry
        uses: ./.github/actions/prepare-poetry
        with:
          python-version: '3.10'

      - name: Build
        run: |
          poetry build

      - name: Display folder
        shell: bash
        if: always()
        run: |
          echo "::debug::listing folder"
          ls -R
          echo `ls -R`
          echo "GITHUB_WORKSPACE ${{ github.workspace }}"
          echo `ls GITHUB_WORKSPACE ${{ github.workspace }}`

      - name: Save build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Build-Artifact
          if-no-files-found: error
          path: ${{ github.workspace }}/dist

  publish:
    name: Publish to PyPI
    needs: [build]
    runs-on: ubuntu-latest
    steps:

      # Retrieve the code and GIT history so that poetry-dynamic-versioning knows which version to upload
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: Build-Artifact
          path: ${{ github.workspace }}/dist

      - name: Install poetry
        uses: ./.github/actions/prepare-poetry
        with:
          python-version: '3.10'

      - name: Upload to PyPI TEST
        run: |
          poetry config repositories.test-pypi https://test.pypi.org/legacy/
          poetry config pypi-token.test-pypi ${{ secrets.POETRY_PYPI_TEST_TOKEN_VALUE }}
          poetry publish --repository test-pypi
